### PR TITLE
#329 | Add token to MM

### LINKED ISSUE #329: Add the option "add token to Metamask" to token menu on the balance row page
# Description
we need to provide an easy way to add tokens to Metamask and one of the best ways is to include the option on the token menu in the balances page.

image

## Consider
- Detect if the user is connected to metamask to show the button
- Teloscan has an implementation for it

### PR DESCRIPTION
**Pull request by EJSG**
# Fixes #329

## Description
Adds the ability to track a token in metamask if using metamask 

## Test scenarios
- go to https://deploy-preview-361--wallet-staging.netlify.app/
- sign in
- click on the overflow menu button next to each token
    - all except the TLOS row should have a menu item to add token to MM
- click one of the `add to MM` entries
    - a MM window should pop up with the correct icon and balance
    - add the token to MM(you can remove later if you want)
- check _Metamask > assets > {asset you added} > overflow menu > token details > token contract address_ and compare to the real token contract address (get that from _teloscan > your address > tokens tab > click token name/address_)
    - the addresses should match
- attempt to add another token to MM but reject the MM window
    - you should get an appropriate error message

## Checklist:

-   [x] I have performed a self-review of my own code
-   [x] I have commented my code, particularly in hard-to-understand areas
-   [x] My changes generate no new warnings
-   [x] I have checked my code and corrected any misspellings
-   [x] I have included all english text to the translation file

### CODE REVIEW

**Review by Viterbo — APPROVED** [review]
It works perfectly :100: 
Great Job !!
image

**Review by pmjanus — APPROVED** [review]

**Comment by pmjanus** [comment]
Testing in iOS chrome I do not get the add to metamask button on sTLOS or wTLOS when connected through walletconnect metamask

**Comment by pmjanus** [comment]
On iOS metamask (not through walletConnect) 2 things happen, 
1. the balance list is not populated with any tokens so I 
2. cannot see the token more menu and add them to metamask

**Review by donnyquixotic — APPROVED** [review]

**Comment by EJSG** [comment]
> On iOS metamask (not through walletConnect) 2 things happen,
> 
> 1. the balance list is not populated with any tokens so I
> 2. cannot see the token more menu and add them to metamask

can you put up a screenshot of this? i can't reproduce on iOS - metamask or safari or brave

> Testing in iOS chrome I do not get the add to metamask button on sTLOS or wTLOS when connected through walletconnect metamask

also for this, this is expected. on iOS no browser can inject metamask. the metamask API is therefore not available to use and add tokens. whether the `add to metamask` item shows up is controlled by `evmStore.isMetamaskSupported` which returns false on iOS generally-- on metamask browser, safari, and brave

**Pull request merged**
