### PR TITLE
#200 | Epic - Wrap/Unwrap

### LINKED ISSUE #200: Wrap/Unwrap TLOS | Epic
## Overview
As a user I want to be able to wrap TLOS and unwrap wTLOS, so I can use telos as an erc20 token.

https://www.figma.com/file/eIpbnt6vqwqptEbZWtwO8Y/v0.3?type=design&node-id=1166-103236&t=8MXvABgxsKLnfNZY-4

## Issues
- https://github.com/telosnetwork/telos-wallet/issues/440
- https://github.com/telosnetwork/telos-wallet/issues/441
- https://github.com/telosnetwork/telos-wallet/issues/442
- https://github.com/telosnetwork/telos-wallet/issues/443

### PR DESCRIPTION
**Pull request by ezra-guzman**
# Fixes #200

## Description
This feature branch PR comprises all of the work from #440, #441, #442, and #443. 

## Test scenarios
- go to https://deploy-preview-530--wallet-staging.netlify.app/
- log in with an account that has TLOS available
- click the overflow menu button on the **TLOS** row in the wallet balance tab
    - it should have an item 'Wrap' which should link to the Wrap page
- click the overflow menu button on the **WTLOS** row in the wallet balance tab
    - it should have an item 'Unwrap' which should link to the Wrap page - unwrap tab
- click the overflow menu button on any other row in the wallet balance tab
    - it should not have an item 'Unwrap' or 'Wrap'
- click the wrap link in the site nav
     - the page should match [the design](https://www.figma.com/file/eIpbnt6vqwqptEbZWtwO8Y/v0.3?type=design&node-id=364-2714&mode=design&t=NSq6quC6Hzmsvc1l-0)
- try wrapping TLOS
    - you should be able to wrap successfully
    - the balance son the page should update once the tx is complete (check the header and the amount above the currency input)
- go to the unwrap tab
    - page should match [the design](https://www.figma.com/file/eIpbnt6vqwqptEbZWtwO8Y/v0.3?type=design&node-id=364-2721&mode=design&t=NSq6quC6Hzmsvc1l-0)
- unwrap some TLOS
    - you should be able to unwrap successfully
    - the balance son the page should update once the tx is complete (check the header and the amount above the currency input)
- repeat these steps on iOS (safari, metamask app, safepal app), android (chrome, metamask app, safepal app), and desktop (metamask, safepal)

## Checklist:

-   [x] I have performed a self-review of my own code
-   [x] I have commented my code, particularly in hard-to-understand areas
-   [x] I have cleaned up the code in the areas my change touches
-   [x] My changes generate no new warnings
-   [ ] Any dependent changes have been merged and published in downstream modules
-   [x] I have checked my code and corrected any misspellings
-   [x] I have removed any unnecessary console messages
-   [x] I have included all english text to the translation file and/or created a new issue with the required translations for the currently supported languages
-   [x] I have tested for mobile functionality and responsiveness
-   [ ] I have added appropriate test coverage

### CODE REVIEW

**Review by donnyquixotic — APPROVED** [review]

**Review by donnyquixotic — CHANGES_REQUESTED** [review]
For SafePal, wrapping functionality works fine (desktop extension), unwrap does not do anything (no errors in console).

**Comment by Viterbo** [comment]
>

**Review by donnyquixotic — APPROVED** [review]

**Comment by pmjanus** [comment]
# 530 Review Telos Wallet

https://deploy-preview-530--wallet-staging.netlify.app/evm/wallet?tab=balance

1. Network switched successfully → Network Switched to XX success type
2. When you go to wrap page, the late loading of the balance gives page a janky effect. (Everything moves down a little bit)
3. Tested Desktop Chrome:
    1. Metamask: Unwrap and Wrap worked
    2. Safepal Through WalletConnect QR on Android: Unwrap and Wrap Worked
4. Tested Mobile:
    1. Safepal Extension:
    2. Metamask Walletconnect:
        1. On telos evm mainnet connecting to testnet site:
            1. Connects successfully while app is on wrong network but get correct balances on site.
            2. When I try to wrap the metamask app asked me to swap network but returned to browser before I selected
            3. wrap button was left perma loading
        2. Metamask closed, on telos testnet:
            1. Wrap 1 tlos worked fine
            2. unwrap 1 tlos 
                1. I could not get the button to register the unwrap 1 tlos
                2. I clicked on 1.0000 tlos available without the button registering
                3. i input 0.9 and the button registered
                4. I did not choose the metamask option because I was wondering wtf 
                5. unwrap remained in loading state permanently
                6. I think this might have to do with the quantity 1.0000 not being exactly 1? unsure

**Comment by ezra-guzman** [comment]
put into draft while I investigate balances issue. sometimes loggedBalances is empty, but sometime scurrentBalances doesn't have WTLOS. both of these need to be solved because they are breaking the wrap page header

**Review by pmjanus — APPROVED** [review]

**Pull request merged**
