### PR TITLE
Only check network before transactions

### LINKED ISSUE #760: switch chains prompt
**Description**
Only prompt users to switch chain (if on different chain) when signing transactions. Currently the user may be switching chains for many different reasons and we don't want to repeatedly bombard the user with switch prompts unnecessarily. Remove automatic chain switch prompts on page load and only prompt when required.

**Actions that require signer (switch chain prompt) :**

- [ ] Stake, Unstake, Withdraw
- [ ] Wrap, Unwrap
- [ ] Send Token
- [ ] Transfer NFT
- [ ] Revoke Approvals

Any other actions that do not require a signer such as contract 'read' actions should use a default provider.

Related Issue: https://github.com/telosnetwork/teloscan/issues/515

### PR DESCRIPTION
**Pull request by Viterbo**
# Fixes #760

## Description
This PR includes a new function `assertNetworkConnection` for the account store that will prompt the user to change the network and block the code until the user either refuses or accepts and effectively changes the network. That allowed us to reduce a lot of redundant code repeated in several places.

image

It also removes the code responsible for warning the user that a network switch has been detected because we don't need it if we are only displaying data. However, when the user tries to sign a transaction we need to explicitly check the network and prompt the user to change it.

## Test scenarios
- [Login using Metamask](https://deploy-preview-763--wallet-develop-mainnet.netlify.app/)
- Once logged, open Metamask, change the network, and come back to the web app
  - you should not get any notification
  - you should be able to explore all sections and your data should be correct
- got to any transaction page and try to perform one: send, wrap, unwrap, etc
  - you should be prompted to change the network
  - if you refuse to switch the network, the transaction cancels quietly
  - if you cancel the switch you get a neutral notification
  - if you accept and continue until effectively change the network, the transaction should go on without the need for you to hit the action button again (see the video).

## Screen captures

[telos-wallet--switch-network-before-trx.webm](https://github.com/telosnetwork/telos-wallet/assets/4420760/7f7d8551-347b-4ff7-947c-d1706c95d575)

## Checklist:

-   [x] I have performed a self-review of my own code
-   [x] I have commented my code, particularly in hard-to-understand areas
-   [x] I have cleaned up the code in the areas my change touches
-   [x] My changes generate no new warnings
-   [x] Any dependent changes have been merged and published in downstream modules
-   [x] I have checked my code and corrected any misspellings
-   [x] I have removed any unnecessary console messages
-   [x] I have included all english text to the translation file and/or created a new issue with the required translations for the currently supported languages
-   [ ] I have tested for mobile functionality and responsiveness
-   [ ] I have added appropriate test coverage

### CODE REVIEW

**Review by donnyquixotic — CHANGES_REQUESTED** [review]
@Viterbo 
- Remove the switch notification altogether, add a network check and switch prompt to any signed transaction

- remove network switch prompt on autologin

**Comment by Viterbo** [comment]
> @Viterbo
> 
> * Remove the switch notification altogether, add a network check and switch prompt to any signed transaction
> * remove network switch prompt on autologin

DONE!

**Comment by Viterbo** [comment]
> @Viterbo Cannot transfer NFTs if on a different network (no switch prompt). Attempts to send on incorrect network fail to estimate gas or execute as an empty transaction (no transfer).

DONE!

**Comment by ezra-sg** [comment]
I noticed a problem which is totally not your fault, as it is present in prod, but i think it might fall under the purview of this issue. maybe you can fix it for this PR, what do you think? if not we can make a separate issue to fix it.

On the approvals page, if you attempt to modify an approval while on the wrong network, the transaction will be on the wrong network (note how it says ethereum mainnet):
image

**Review by donnyquixotic — DISMISSED** [review]

**Review by donnyquixotic — APPROVED** [review]

**Pull request merged**
